apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: hw5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        env:
          - name: REDMINE_DB_POSTGRES
            value: database
          - name: REDMINE_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret3
                key: user
          - name: REDMINE_DB_DATABASE
            value: testdatabase
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret3
                key: password
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: mysecret3
                key: redminesecret
        ports:
        - containerPort: 3000
